services:
  rent-api:
      build:
        dockerfile: Smart.RentService.WebAPI/Dockerfile
        context: .
      environment:
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_ENVIRONMENT=Development
        - DOTNET_RUNNING_IN_CONTAINER=true
      ports:
        - "5000:80"
        - "44388:443"
      depends_on:
        - db
      networks:
        - sql
    

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongDatabasePassword123@
    networks:
      - sql

networks:
  sql:
    driver: bridge
    name: sql_network